### ISSUE TITLE
schema is not generated with validation when comment includes Japanese

### ISSUE THREAD

**Issue by manak1** [chrishoermann/zod-prisma-types#118]
Hello, Thank you for creating a wonderful package!
I have a problem generating schema with validation using Japanese error message.
Is there any workaround for this problem? 👀

```schema.prisma
datasource db {
  provider  = "postgres"
}

generator zod {
  provider = "zod-prisma-types"
}

model User {
  id String @id @default(uuid())
  /// @zod.string({ required_error: 'required' })
  email String 
  /// @zod.string({ required_error: '必須項目です' })
  password String
}
```
### Expected output
```index.ts
export const UserSchema = z.object({
  id: z.string().uuid(),
  email: z.string({ required_error: 'required' }),
  password: z.string({ required_error: '必須項目です' }),
})

```

### Actual output
```index.ts
export const UserSchema = z.object({
  id: z.string().uuid(),
  email: z.string({ required_error: 'required' }),
  /**
   * ({ required_error: '必須項目です' })
   */
  password: z.string(),
})
```

**Comment by chrishoermann** [comment]
@manak1 thanks for pointing this out. since I'm using regexes quite heavily to validate if the user input is valid this is due to the fact that I do not check for Japanese characters since I do not speak nor can I read your language - so sadly  Ihave no idea how to check for these characters:

maybe you could open a PR or provide some info on how to check for Japanese in the regex?

**Comment by manak1** [comment]
@chrishoermann 
Thank you for your response! 
I'm not really familiar with regex but I will check it out 👀

**Comment by dbtl88** [comment]
Not sure how helpful this still might be, but this should work to match all Japanese text:

`[\p{sc=Hira}\p{sc=Kana}\p{sc=Han}]`

Which is the same as (using the combined hiragana / katakana unicode script identifier):

`[\p{sc= Hrkt}\p{sc=Han}]`

Explanations can be found here:
[how to do regex on Unicode script identifiers](https://unicode.org/reports/tr18/) (section 1.2.6)
[the list of Unicode script identifiers](https://en.wikipedia.org/wiki/Script_(Unicode)#List_of_scripts_in_Unicode)

Note I've also included the 'Han' script identifier, i.e. all of the possible Kanji.

**Comment by chrishoermann** [comment]
I implemented the behaviour as suggested by @dbtl88 and according to my tests it works. Would be nice if someone could confirm this with a more extended range of japanese characters than the ones I used in my tests.

**Comment by iStorry** [comment]
Well this is not working as expected. 

```ts
 email String @unique /// @zod.custom.use(z.string().email({ message: "メールアドレスを入力してください" }))

  /// @zod.custom(z.string({ message: "メールアドレスを入力してください" }).email({ message: "有効なメールアドレスを入力してください" }))
  /// @zod.custom(z.string({ message: "パスワードを入力してください" }).min(8, { message: "パスワードは8文字以上で入力してください" }))
  password String```

![image](https://github.com/chrishoermann/zod-prisma-types/assets/7252344/88dbab2a-a06f-4b57-a98c-0f480d3891b7)
