### ISSUE TITLE
Custom imports with hyphen "-" in name won't match with import regex

### ISSUE THREAD

**Issue by FireMakeThunder** [chrishoermann/zod-prisma-types#124]
I was attempting to use the custom import with a `-` but the generator wouldn't pick it up because `IMPORT_STATEMENT_REGEX` and `IMPORT_STATEMENT_REGEX_PATTERN` won't match import statements that include `-`.

```prisma
/// @zod.import(["import { myFunction } from '$lib/zod-schemas';"])
```

Adding hypen to the two regexes should fix the problem.

**Comment by chrishoermann** [comment]
@FireMakeThunder merged your PR into latest version.
