### ISSUE TITLE
Add Support for Bytes type

### ISSUE THREAD

**Issue by chrishoermann** [chrishoermann/zod-prisma-types#13]
the bytes type is supported by prisma.
to add support further investigation is needed: 

maybe `z.instanceOf(Buffer).nullable()` would be sufficient like described in this article

https://bytemeta.vip/repo/colinhacks/zod/issues/925

**Comment by chrishoermann** [comment]
implemented by printing

```ts
const myBufferType = z.instanceof(Buffer)
```

**Comment by yamiteru** [comment]
This doesn't work in a Cloudflare Worker since `Buffer` is NodeJS specific API. Would it be possible to use `UInt8Array` instead?

**Comment by chrishoermann** [comment]
@yamiteru I think this is something that needs to be changed on the Prisma side since they use `Buffer` in their types and I don't know if this would work if we change it to `UInt8Array` and it stays `Buffer` in the prisma types? Do you have any insights on this?
I also think that the Prisma team is aware of the problem of Prisma with cloudflare and edge in general.

**Comment by mgloc** [comment]
Even when omitting input + model on a field of type Bytes, there is still some usage of Buffer somewhere in the file, resulting in an error when importing an unrelated schema client-side compatible on client. Could it be possible to have an option to declare it at any, without validator or something similar ?
