### ISSUE TITLE
Is it possible to skip `prismaClientPath` and the import line?

### ISSUE THREAD

**Issue by zeferinix** [chrishoermann/zod-prisma-types#130]
My use case is to use this library purely for generating zod schemas then use a different ORM or Query Builder which means I don't need `@prisma/client`.

![image](https://user-images.githubusercontent.com/6721822/231733292-61e55328-2339-4530-bc50-5b375c50acf2.png)

Seems like whatever I put on the `prismaClientPath` just gets interpolated to the import path but I'd want the import line removed.

**Comment by chrishoermann** [comment]
This sadly is not possible, because many generated schemas rely on the imported `Prisma` type to work correctly.

**Comment by zeferinix** [comment]
I see. Would've been nice for an option to make it decoupled or opt-in to Prisma Client since I'm only opting for the models to be generated and the rest disabled (so no Prisma type dependency) but alright, guess we can close this issue. Thanks!
