### ISSUE TITLE
Add `--prettier` flag to support auto-formatting output file

### ISSUE THREAD

**Issue by andenacitelli** [chrishoermann/zod-prisma-types#131]
This library exposes an option like that: https://github.com/astahmer/openapi-zod-client

While it's easy to simply create a `.prettierignore` and an `.eslintignore` file with the output in it, or to automatically run prettier afterwards, I figure I may as well suggest adding this kind of option. Not high priority or anything, just something I think would make a positive addition.

**Comment by fogx** [comment]
this was marked completed, but i does it exist? Looking for this as well.
