### ISSUE TITLE
Merging input types

### ISSUE THREAD

**Issue by wowczarczyk** [chrishoermann/zod-prisma-types#140]
Hey, great library!

I am working on a T3 app and wanted to use this lib to reduce boilerplate for input types to tRPC mutations. I got stuck a bit with the need of merging two generated *Input types:

```
add: protectedProcedure
    .input(
      DoctorCreateInputSchema.merge(MedicalFacilityCreateInputSchema).merge(
        z.object({ doctorName: z.string() })
      )
    )
 ```
 
The generated types are explicitly typed as `ZodType` that does not seem to have the `.merge()` function as it belongs to `ZodObject`. Any ways of circumventing this problem?

**Comment by wowczarczyk** [comment]
I saw this post https://github.com/chrishoermann/zod-prisma-types/issues/79 and indeed this works by utlizing the `****OptionalDefaultsSchema` types instead of the input types, not sure how elegant this is ;) 

Also I think that if the input types could not be typed as `ZodType<...>` but rather by the new `satisfies ZodTyps<...>` operator this could help as well

**Comment by wowczarczyk** [comment]
I saw this post https://github.com/chrishoermann/zod-prisma-types/issues/79 and indeed this works by utlizing the `****OptionalDefaultsSchema` types instead of the input types, not sure how elegant this is ;) 

Also I think that if the input types could not be typed as `ZodType<...>` but rather by the new `satisfies ZodTyps<...>` operator this could help as well

**Comment by chrishoermann** [comment]
@wowczarczyk thanks for reaching out. I actually tried using the `satisfied` keyword but there is a limitation of zod that a specific type annotation is needed when recursive types are used as stated [in the docs](https://zod.dev/?id=recursive-types). So sadly it is not possible to switch to this solution because prisma types heavily rely on recursion.
