### ISSUE TITLE
Type error with newer versions

### ISSUE THREAD

**Issue by aronmal** [chrishoermann/zod-prisma-types#141]
Hey there, I recently updated my packages and encountered problems when building my nextjs application. I have reverted to the 'old' versions, but I thought I report my findings to you.

My prisma file:
[schema.prisma.TXT](https://github.com/chrishoermann/zod-prisma-types/files/11475466/schema.prisma.TXT)

Working dependencies:
```
    "@prisma/client": "^4.12.0",
    "prisma": "^4.12.0",
    "zod-prisma-types": "^2.5.6",
```

But with these dependencies it does not work:
```
    "@prisma/client": "^4.14.0",
    "prisma": "^4.14.0",
    "zod-prisma-types": "^2.7.1",
```

When I ran `pnpm run build`, I get the following output in my terminal:

info  - Linting and checking validity of types .Failed to compile.

./prisma/generated/zod/index.ts:2874:14
Type error: Type 'ZodObject<{ where: ZodLazy<ZodType<User_GameWhereUniqueInput, ZodTypeDef, User_GameWhereUniqueInput>>; create: ZodUnion<...>; }, "strict", ZodTypeAny, { ...; }, { ...; }>' is not assignable to type 'ZodType<User_GameCreateOrConnectWithoutUserInput, ZodTypeDef, User_GameCreateOrConnectWithoutUserInput>'.
  The types of '_type.create' are incompatible between these types.
    Type '(User_GameCreateWithoutUserInput | User_GameUncheckedCreateWithoutUserInput) & (User_GameCreateWithoutUserInput | User_GameUncheckedCreateWithoutUserInput | undefined)' is not assignable to type '(Without<User_GameCreateWithoutUserInput, User_GameUncheckedCreateWithoutUserInput> & User_GameUncheckedCreateWithoutUserInput) | (Without<...> & User_GameCreateWithoutUserInput)'.
      Type 'User_GameCreateWithoutUserInput & User_GameUncheckedCreateWithoutUserInput' is not assignable to type '(Without<User_GameCreateWithoutUserInput, User_GameUncheckedCreateWithoutUserInput> & User_GameUncheckedCreateWithoutUserInput) | (Without<...> & User_GameCreateWithoutUserInput)'.
        Type 'User_GameCreateWithoutUserInput & User_GameUncheckedCreateWithoutUserInput' is not assignable to type 'Without<User_GameUncheckedCreateWithoutUserInput, User_GameCreateWithoutUserInput> & User_GameCreateWithoutUserInput'.
          Type 'User_GameCreateWithoutUserInput & User_GameUncheckedCreateWithoutUserInput' is not assignable to type 'Without<User_GameUncheckedCreateWithoutUserInput, User_GameCreateWithoutUserInput>'.
            Types of property 'gameId' are incompatible.
              Type 'string' is not assignable to type 'undefined'.

  2872 | }).strict();
  2873 | 
> 2874 | export const User_GameCreateOrConnectWithoutUserInputSchema: z.ZodType<Prisma.User_GameCreateOrConnectWithoutUserInput> = z.object({
       |              ^
  2875 |   where: z.lazy(() => User_GameWhereUniqueInputSchema),
  2876 |   create: z.union([ z.lazy(() => User_GameCreateWithoutUserInputSchema),z.lazy(() => User_GameUncheckedCreateWithoutUserInputSchema) ]),
  2877 | }).strict();

info  - Linting and checking validity of types .. ELIFECYCLE  Command failed with exit code 1.

**Comment by chrishoermann** [comment]
@aronmal Which version of zod are you using. There is a known bug with zod versions greater than `3.21.1` as mentioned in #98.
Maybe this is the cause for the type error?
