### ISSUE TITLE
Entire object as parameter in refine function

### ISSUE THREAD

**Issue by kjavia** [chrishoermann/zod-prisma-types#143]
I am trying to use something similar to this for date validation (start and end dates) for which I need the entire object reference where both dates are a part of. 

`  /// @zod.custom.use(z.string().refine((val) => myFunction(val), { message: 'Is not valid' }))`

However the `val` parameter is just the individual property value being checked. Anyway to get the whole object?

**Comment by chrishoermann** [comment]
@kjavia can you please give me a bit more context with a more detailed example on this one? Are you trying to check if two properties in the schema match a certain criteria or need to compare them?

**Comment by kjavia** [comment]
Yes, I have a table with `start` and `end` dates and I want to make sure the end date is not before the start date. The `zod.refine` method needs to be the entire record, not just the one property being validated. Unless there is a different way of doing it altogether.

**Comment by chrishoermann** [comment]
@kjavia I think i understand.
another expample that comes to my mind would be the validation of a password like:

```ts
const MyObjectSchema = z
  .object({
    password: z.string(),
    passwordConfirmation: z.string(),
  })
  .refine((data) => data.password === data.passwordConfirmation, {
    message: 'Passwords do not match',
    path: ['passwordConfirmation'],
  });
```

This is definitly a good feature but this needs a little work, so it could take a while til it is ready.

**Comment by kjavia** [comment]
> @kjavia I think i understand. another expample that comes to my mind would be the validation of a password like:
> 
> ```ts
> const MyObjectSchema = z
>   .object({
>     password: z.string(),
>     passwordConfirmation: z.string(),
>   })
>   .refine((data) => data.password === data.passwordConfirmation, {
>     message: 'Passwords do not match',
>     path: ['passwordConfirmation'],
>   });
> ```
> 
> This is definitly a good feature but this needs a little work, so it could take a while til it is ready.

Yes this is what I was looking for. This would take the validation to a whole another level.

**Comment by ciscoheat** [comment]
I just bumped into this with a requirement of two field values being exclusive to each other. I'm extending the generated schema in another place for now, but it would be nice to have it built-in.

**Comment by Nerih** [comment]
agreed, it would be wonderful to have this!

**Comment by chrishoermann** [comment]
@ciscoheat @Nerih @kjavia took some time but now this should be ready to go in the latest version - see [docs](https://github.com/chrishoermann/zod-prisma-types#model-validators)

can you please test this with your implementations and see if it works as expected. Would also be nice if you could provide your use cases so I can feed my tests with more data.

**Comment by Nerih** [comment]
> @ciscoheat @Nerih @kjavia took some time but now this should be ready to go in the latest version - see [docs](https://github.com/chrishoermann/zod-prisma-types#model-validators)
> 
> can you please test this with your implementations and see if it works as expected. Would also be nice if you could provide your use cases so I can feed my tests with more data.

Excellent, I'll need to refactor some parts of my code. But will test next week.

Amazing! I'll type up my use case too.

**Comment by kjavia** [comment]
Thanks for the quick turnaround.

**Comment by chrishoermann** [comment]
Closing since it is implemented
