### ISSUE TITLE
Generated types mismatch (Inside NX monorepo lib)

### ISSUE THREAD

**Issue by d-ivashchuk** [chrishoermann/zod-prisma-types#144]
hey @chrishoermann! thanks a lot for building this awesome library - I am now building the dream DX setup with full e2e type-safety, and zod-prisma-types fit well in it. 

I experienced some problems with the simple generation, so it might be something  I don't understand conceptually here:

I have a very minimalistic setup here, just newly generated lib inside NX monorepo.

<img width="159" alt="Screenshot 2023-05-18 at 09 56 17" src="https://github.com/chrishoermann/zod-prisma-types/assets/29632358/4289da67-fdf2-423a-af12-52a26a913d3e">

My schema is super small as well:

```js
generator client {
  provider = "prisma-client-js"
}

generator zod {
  provider = "zod-prisma-types"
  output   = "./zod"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Post {
  id          String   @id @default(cuid())
  createdAt   DateTime @default(now())
  updatedAt   DateTime @updatedAt
  title       String   @db.VarChar(255)
  content     String?
  description String?
  published   Boolean  @default(false)
  tags        String[]
  image       String?
}

```

Straight after running `npx prisma generate` I see the zod output which immediately throws some type errors at me. I guess it's not expected at all :/

<img width="677" alt="Screenshot 2023-05-18 at 09 58 22" src="https://github.com/chrishoermann/zod-prisma-types/assets/29632358/443c6276-50e9-414a-b2ba-3ec9fc4550d7">

Maybe my tsconfigs would be of use here:

`tsconfig.json`

```ts
{
  "extends": "../../tsconfig.base.json",
  "compilerOptions": {
    "module": "commonjs"
  },
  "files": [],
  "include": [],
  "references": [
    {
      "path": "./tsconfig.lib.json"
    }
  ]
}

```

`tsconfig.lib.json`

```ts
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "module": "commonjs",
    "outDir": "../../dist/out-tsc",
    "declaration": true,
    "types": ["node"]
  },
  "exclude": ["jest.config.ts", "src/**/*.spec.ts", "src/**/*.test.ts"],
  "include": ["src/**/*.ts"]
}
```

would really appreciate any advice here, I think that zod-prisma-types is awesome addition to my flow and I really want to use it :D

**Comment by chrishoermann** [comment]
@d-ivashchuk thanks for reaching out. Glad you like the library. There ist a known inkompatibility/bug with zod versions greater than 3.21.1.Maybe this could be the source of the type error?

**Comment by d-ivashchuk** [comment]
I think I rubber duckked myself into solution. If you look at my tsconfigs - I am missing strict type. I tried to look at your example and just see what would make sense. It seems far better now!

**Comment by chrishoermann** [comment]
Another thing that comes to my mind is that in some rare cases the prisma client `index.d.ts` is not updated when changes in the `prisma.schema` are made. This could also result in a type error. Furthermore there are some known issues with casing of the typenames as in #95 and #121

**Comment by d-ivashchuk** [comment]
Everything was working well after I changed the strict mode to true, but it was on prisma v3, now I updated to prisma v4, namely: ` "prisma": "^4.14.1",` and after generation I face this error in generated code:

<img width="698" alt="Screenshot 2023-05-18 at 13 57 20" src="https://github.com/chrishoermann/zod-prisma-types/assets/29632358/33a67ab6-f233-4496-9914-cfa3297b7eea">

Any idea what might be wrong here?

**Comment by chrishoermann** [comment]
@d-ivashchuk did you have any more problems with this issue or is it resolved?

**Comment by d-ivashchuk** [comment]
No, let's close it! The above mentioned fixes worked
