### ISSUE TITLE
Add support for @zod.refine and validator.js

### ISSUE THREAD

**Issue by chrishoermann** [chrishoermann/zod-prisma-types#15]
It would be nice to have support for custom refinement functions like

```ts
z.string().refine(...do something)
// would be reflected in prisma model with
myfield String /// @zod.string.refine(...do something)
```

This refinement function should also work on `non scalar` types:

```ts
z.bigint.refine(...doSomething)
// would be reflected in prisma model with
myfield String /// @zod.custom.refine(...do something)
```

furthermore it would be nice to have validator js capabilities in the refinement functions of strings. (https://github.com/validatorjs/validator.js)
Possible ways of implementing this supporting regex validation:

```ts
z.string().refine(...do something)
// would be reflected in prisma model with
myfield String /// @zod.string.refineWithValidator(...do something)

// then validator js would be added as an import
// the user needs to make shure that the package is installed
```

**Comment by chrishoermann** [comment]
validator.js can be used when specifing `useValidatorJs` in client config

**Comment by chrishoermann** [comment]
@support for `@zod.refine` on scalar fields dropped in favour of `@zod.custom.use(...your refine logic)`

**Comment by kjavia** [comment]
I am using this feature for comparing `start` and `end` dates on my schema record, however it seems that the `refine` function is only receiving the value of the field that is being validated not the entire object. 

```
  /// @zod.custom.use(z.date().refine(schema => (schema.start && schema.end && schema.end < schema.start), { message: 'End date cannot be before start date.'}))

```

`schema` is a date not the parent object. I am on an older version (2.4.1) due to compatibility issues. Not sure if this has been fixed in the later versions.
