### ISSUE TITLE
schema.prisma type descriptions?

### ISSUE THREAD

**Issue by gregg-cbs** [chrishoermann/zod-prisma-types#154]
Hi Chris,

Sorry to bother you but I have a question I couldnt quite find the answer to.

In my prisma.schema I want to add zod comments to types to add a description to zod.
```
/// @zod.object({ description: "The dimensions of the product. This is different to the shipping or boxed dimensions and is usually smaller. If you cannot find the product dimensions make this the same as the dimensions_packed." })
type Dimensions {
  width  Float
  depth  Float
  height Float
  unit   String
}
```

or better yet (this failed because z.object is not equal to Dimensions type)
```
model Product {
  dimensions        Dimensions? /// @zod.object({ description: "The dimensions of the product. This is different to the shipping or boxed dimensions and is usually smaller. If you cannot find the product dimensions make this the same as the dimensions_packed." })
  dimensions_packed Dimensions? /// @zod.object({ description: "The boxed / shipping / packaged dimensions of the product." })
}
```

Neither method was successful in adding the descriptions to zod.

**Comment by chrishoermann** [comment]
@gregg-cbs the first example should work now in the latest version when using

```prisma
/// @zod.describe("some description")
model MyModel {
...fields
}
```

for the second one there is no solution implemented yet

**Comment by gregg-cbs** [comment]
Thanks. I have since moved on from this project using prisma. I appreciate the response. Hopefully this will help others out there.
