### ISSUE TITLE
Field writeBarrelFiles actually set to false by default

### ISSUE THREAD

**Issue by enfipy** [chrishoermann/zod-prisma-types#160]
As the title of this issue said - the actual value is set to "false" [here](https://github.com/chrishoermann/zod-prisma-types/compare/v2.7.2...v2.7.4#diff-4751e8c963cee473f9b2522c38a01e11bfb98504f0482952b7159e4ecf0819d8R13).

A possible solution is to change the default value or change documentation, I don't know which one is better so just putting this small issue here.

P.S.: Thank you for your work and this wonderful library!

**Comment by chrishoermann** [comment]
Thanks for pointing this out. this was not intentional. the default should have been `true`. Should be fixed in the lates version
