### ISSUE TITLE
Support prisma 5.0.0

### ISSUE THREAD

**Issue by ytnobody** [chrishoermann/zod-prisma-types#161]
In 3 days ago, prisma 5.0.0 has been released.

https://github.com/prisma/prisma/releases/tag/5.0.0

**Comment by andenacitelli** [comment]
Leaving a specific error here that I believe Prisma 5.x.x introduces

```sh
./prisma/generated/zod/index.ts:556:45
Type error: Cannot find name 'StringFieldRefInputSchema'.

  554 |
  555 | export const StringFilterSchema: z.ZodType<Prisma.StringFilter> = z.object({
> 556 |   equals: z.union([ z.string(),z.lazy(() => StringFieldRefInputSchema) ]).optional(),
      |                                             ^
  557 |   in: z.union([ z.string().array(),z.lazy(() => ListStringFieldRefInputSchema) ]).optional(),
  558 |   notIn: z.union([ z.string().array(),z.lazy(() => ListStringFieldRefInputSchema) ]).optional(),
  559 |   lt: z.union([ z.string(),z.lazy(() => StringFieldRefInputSchema) ]).optional(),
```

Schema:

```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

generator zod {
  provider = "zod-prisma-types"
}

model User {
  // non-user-facing information about a user
  id    String @id @default(uuid()) @map("_id")
  email String @unique

  // Linkage
  Profile Profile?

  // Audit
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}

model Profile {
  // publicly facing information for ANY given user; only generalized attributes are here
  id String @id @default(uuid()) @map("_id")

  // Requested at initial onboarding
  role      UserRoles
  firstName String
  lastName  String
  fullName  String // Computed as `firstName lastName`

  // Users can optionally adjust these at a later point
  bio      String  @default("")
  imageUrl String? // TODO: Implement actual hosting for these on something like Vercel Blob or S3
  school   String? // TODO: Should eventually be a "search first, if you can't find, create your own" system. Or, pull a dataset and have people reach out if their school isn't listed.

  // Athletes can flag certain coaches that have some edit permissions on their profile
  coachIds String[]

  // Linkage
  user   User   @relation(fields: [userId], references: [id], onDelete: Cascade)
  userId String @unique

  // Audit
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}

model School {
  id       String @id @default(uuid()) @map("_id")
  name     String
  location String

  @@unique([name, location])
}

enum UserRoles {
  ATHLETE
  COACH
  RECRUITER
  DOCTOR
}
```

**Comment by nordowl** [comment]
> Leaving a specific error here that I believe Prisma 5.x.x introduces

This was my experience aswell. I believe all of the `XXXXFieldRefInputSchema` variables are undefined.
I compared the generated types of Prisma 5 and 4.16, and it seems like Prisma 5 generates those union types, which Prisma 4.16 did not.

Prisma 5
`equals: z.union([ z.boolean(),z.lazy(() => BooleanFieldRefInputSchema) ]).optional(),`

Prisma 4.16
`equals: z.boolean().optional(),`

**Comment by renatoaraujoc** [comment]
Any ETA for supporting Prisma 5? :/

**Comment by chrishoermann** [comment]
I gave it a quick look and the `fieldRef` feature is used to compare columns in the same table - as stated in the [docs](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#compare-columns-in-the-same-table)

To my understanding this is not possible to implement via zod schemas because, the field refs need direct access to the `prisma client instance` - which we do not have.

So to make the generator compatible for now I'll filter out all the `fieldRefs` and just expose the `nonFieldRef` types as it was prior to `prisma 5.0.0.` and see if it works.

**Comment by renatoaraujoc** [comment]
@chrishoermann not related to this post but if you could take a look on how to implement (or make it easier) to use `.pick()` / `.omit()` on nested relations it'd be amazing.

This is my code today:

```typescript
const actOrgansSchema = ActOrganSchema.pick({
    id: true,
    initials: true,
    name: true,
    enabledClient: true,
    stateId: true,
    countryId: true,
    municipalityId: true
}).merge(
    z.object({
        country: countrySchema,
        state: stateSchema.nullable(),
        municipality: municipalitySchema.nullable(),
        _count: z.object({
            acts: z.number()
        })
    })
);
``` 

Preferable way:

```typescript
const actOrgansSchema = ActOrganSchema.pick({
    id: true,
    initials: true,
    name: true,
    enabledClient: true,
    stateId: true,
    countryId: true,
    municipalityId: true,
    // relation here, this organ belongs to a country that has id, name, etc
    country: {
        id: true,
        name: true
    }
});
```

Sorry for writing in this issue, I can delete if you want.

**Comment by chrishoermann** [comment]
I removed the 'fieldRef' in the latest version and fixed some other bugs. Can you please see if the problems are fixed on your end too and if there are any errors left related to `prisma 5.x`?

**Comment by renatoaraujoc** [comment]
> I removed the 'fieldRef' in the latest version and fixed some other bugs. Can you please see if the problems are fixed on your end too and if there are any errors left related to `prisma 5.x`?

I just updated to your latest version and I'm now getting this.

![Screenshot 2023-08-03 at 17 32 13](https://github.com/chrishoermann/zod-prisma-types/assets/358128/f9586b91-6650-4c98-9922-dc1e72a6589a)
![Screenshot 2023-08-03 at 17 34 56](https://github.com/chrishoermann/zod-prisma-types/assets/358128/658abbf2-5c8a-45b9-b833-11b67a49f758)

You fixed the `fieldRef` thing but introduced some sort of Model`Default`Args that do not exist on my Prisma.

I'm using Prisma v5.0.0.

**Comment by chrishoermann** [comment]
@renatoaraujoc thanks for the information. have you tried to delete the generated prisma client in the `node_modules` folder? 
I had a similar issue once when there were both clients - in your case from `v5.0.0` and `v5.1.1` - present in the node modules folder. Somehow typescript didn't get the notice and still referred to the old version during compilation. I solved it by deleting the whole `node_modules` folder and ran the install and generation again. maybe this solves the issue. otherwise please let me know and we'll see if I can solve this without your schema.

**Comment by renatoaraujoc** [comment]
> 

I've done a full re-install of everything, didn't work, same error.
I'm now trying a full re-install with a new generated yarn.lock.
I will get back to you soon.

**Comment by renatoaraujoc** [comment]
@chrishoermann I did a full re-install with removed node_modules and no luck, same error, emptied all caches as well.
I'm trying now with a new yarn.lock (backed up the old one).
I'll get back to you soon.

**Comment by chrishoermann** [comment]
@renatoaraujoc which version of zod are you on?

**Comment by renatoaraujoc** [comment]
> @renatoaraujoc which version of zod are you on?

```
zod@^3.21.1, zod@^3.21.4:
  version "3.21.4"
  resolved "https://registry.yarnpkg.com/zod/-/zod-3.21.4.tgz#10882231d992519f0a10b5dd58a38c9dabbb64db"
  integrity sha512-m46AKbrzKVzOzs/DZgVnG5H55N1sv1M8qZU3A8RIKbs3mrACDNeIOeilDymVb2HdmP8uwshOCF4uJ8uM9rCqJw==
```

**Comment by chrishoermann** [comment]
@renatoaraujoc are both versions installed? please use `3.21.1` exclusively. there is a known bug with higher versions of zod that needs to be adressed by the zod team. maybe this fixes the issue.

**Comment by renatoaraujoc** [comment]
@chrishoermann I'll test with exact v3.21.1 soon and will get back to you.

**Comment by samrocksc** [comment]
I got it to work right with the following packages, I'm using an nx monorepo for this one:

```
"zod": "3.21.1",
"zod-prisma-types": "^2.7.7",
"@prisma/client": "^5.1.1",
```

**Comment by jonsoku2** [comment]
### package.json
```json
    "zod": "3.21.1",
    "zod-prisma-types": "^2.7.9",
    "@prisma/client": "^5.2.0",
    "prisma": "^5.2.0"
```

it works for me on nestjs project.
i changed strictNullChecks from `false` to `true`, strictNullChecks `false` is the default setting for tsconfig of nestjs.

**Comment by Digital39999** [comment]
I can't get it to work on your configuration @jonsoku2, always getting following error:
- Type 'string' is not assignable to type 'undefined'.

Here's my config:
```prisma
generator zod {
  provider = "zod-prisma-types"
  output= "./zod"
  createPartialTypes = true
  validateWhereUniqueInput = true
  createRelationValuesTypes = true
  createOptionalDefaultValuesTypes = true
}
```

Package: 
```json
"dependencies": {
  "@prisma/client": "5.2.0",
  "prisma": "5.2.0",
  "zod": "^3.21.1",
  "zod-prisma-types": "^2.7.9"
},
```

And TSConfig: 
```json
{
  "compilerOptions": {
    "module": "CommonJS",
    "target": "ES2022",
    "sourceMap": true,
    "outDir": "./dist",
    "skipLibCheck": true,
    "noImplicitAny": true,
    "declaration": true,
    "strict": true,
    "strictNullChecks": true,
    "esModuleInterop": true,
    "baseUrl": "./"
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules"]
}
```

Any idea?

**Comment by chrishoermann** [comment]
I'm closing this issue since the  latest version of the generator `2.7.13` should work with the latest prisma version `5.4.2`.
