### ISSUE TITLE
How to tell zod generator that autogenerated id fields shouldn't be included for safeParsing

### ISSUE THREAD

**Issue by FaresKi** [chrishoermann/zod-prisma-types#162]
Hi!
Great plugin, super handful.
I just got a quick question.
I got a schema model similar to the following:
```prisma
model Users {
  id        Int        @id @default(autoincrement())
  firstName String     @db.VarChar(50)
  lastName  String     @db.VarChar(50)
  email     String     @unique @db.VarChar(100)
   ...
}
```
The plugin generates the zod schema, which is helpful:

```ts
export const UsersSchema = z.object({
	id: z.number().int(),
	firstName: z.string(),
	lastName: z.string(),
	email: z.string(),
         ...
})
```
But I want `id` to be considered optional, so when it comes to creating users, i don't need it to be there.
How can I do so?

Thanks!

**Comment by CyanoFresh** [comment]
you can use 
```js
UsersSchema.omit({ id:true })
```
or 
```js
UsersSchema.extend({
   id: z.number().nullish()
})
```

**Comment by creising** [comment]
I ran into the same issue and used the [omit annotation](https://github.com/chrishoermann/zod-prisma-types#omit-fields) which removed it from the schema entirely. Alternatively, you can have fields with default values marked as optional by enabling [this feature](https://github.com/chrishoermann/zod-prisma-types#createoptionaldefaultvaluestypes).
