### ISSUE TITLE
Enums are stored in inputTypeSchemas even if generation of input types is disabled

### ISSUE THREAD

**Issue by CyanoFresh** [chrishoermann/zod-prisma-types#164]
Hi!
I have such prisma config:
```prisma
generator zod {
  provider                 = "zod-prisma-types"
  output                   = "../schema/src/prisma-generated"
  useMultipleFiles         = true
  writeBarrelFiels         = false
  createInputTypes         = false
  addIncludeType           = false
  addSelectType            = false
  writeNullishInModelTypes = true
}
```

but enums are generated inside `inputTypeSchemas` folder anyway:

```ts
import { z } from 'zod';

export const AssignmentTypeSchema = z.enum(['GROUPS','TEAMS','LOB','OTHER']);

export type AssignmentTypeType = `${z.infer<typeof AssignmentTypeSchema>}`

export default AssignmentTypeSchema;
```

Can we add an option to generate "in-place" enums and other types that are stored now in `inputTypeSchemas` folder?

**Comment by chrishoermann** [comment]
@CyanoFresh thanks for reaching out. I located the enums in the `inputTypeFolder` because otherwise in `useMultipleFile` mode imports would have been a real pain to get working - this would also be the case with `in-place` enums. So sadly this is not an option I'm currently considering.
