### ISSUE TITLE
Prisma has no exported member named '***DefaultArgs'

### ISSUE THREAD

**Issue by samrocksc** [chrishoermann/zod-prisma-types#171]
## Overview
I am having an issue with  `Args` vs. `DefaultArgs`

## Versions used

- 4.16.1

## Schema

```schema.prisma
generator client {
  provider      = "prisma-client-js"
  binaryTargets = ["linux-musl", "debian-openssl-3.0.x", "debian-openssl-1.1.x"]
}

datasource db {
  provider = "mongodb"
  url      = env("DATABASE_URL")
}

generator zod {
  provider                         = "zod-prisma-types"
  createRelationValuesTypes        = true
  writeNullishInModelTypes         = true
  createOptionalDefaultValuesTypes = true
  useMultipleFiles                 = true // default is false
  writeBarrelFiles                 = false // default is true
  createInputTypes                 = true // default is true
  createModelTypes                 = true // default is true
  addInputTypeValidation           = true // default is true
  addIncludeType                   = true // default is true
  addSelectType                    = true // default is true
  validateWhereUniqueInput         = false // default is false
  createPartialTypes               = false // default is false
  useDefaultValidators             = true // default is true
  coerceDate                       = true // default is true
}

model User {
 id        String   @id @default(auto()) @map("_id") @db.ObjectId
  name  String
  email String @unique
  posts Post[]
}

model Post {
  id        String   @id @default(auto()) @map("_id") @db.ObjectId
  title    String
  content  String
  author   User   @relation(fields: [authorId], references: [id])
  authorId String @db.ObjectId
}
```

## Unexpected Behavior

![image](https://github.com/chrishoermann/zod-prisma-types/assets/558796/dbbe1e72-421e-44b7-b860-e1bf4d015fcb)

**code causing this**
```typescript
// Error is flagged on `PostDefaultArgs`
export const PostArgsSchema: z.ZodType<Prisma.PostDefaultArgs> = z.object({
  select: z.lazy(() => PostSelectSchema).optional(),
  include: z.lazy(() => PostIncludeSchema).optional(),
}).strict();
```
I am just not familiar enough with how things are getting written to really be able to fix this right now.  I'll try and dig into it this weekend.

Does anyone have a work around or anything?  Really excited about the library, but this bug kind of makes it unusable with barrelfiles or in a single file unfortunately.

I found the culprit here:  I'll have to dig into it and find out

https://github.com/chrishoermann/zod-prisma-types/blob/ac87ff3a1a8bebf121176c6229877c6aeb23115f/packages/generator/src/functions/contentWriters/writeArgs.ts#L36

Now what's interesting is I can just use `PostArgs` and everything works as intended!  So we're already close to the fix.

**Comment by chrishoermann** [comment]
@samrocksc are you on prisma 5.1.1? They introduced some type renaming in one of the latest updates.

**Comment by samrocksc** [comment]
Prisma 4.16.1 and then I tried with 5, but the same issue happens, i can try a few other configurations.

**Comment by chrishoermann** [comment]
did you specifically try `prisma 5.1.1`? this fixed the issue in [this case](https://github.com/chrishoermann/zod-prisma-types/issues/161#issuecomment-1664613175)

**Comment by chrishoermann** [comment]
It seems `prisma` introduced more breaking changes in their typings from `4.x.x.` to `5.1.1` that I need to be aware of and that need to be stated in the docs.

**Comment by samrocksc** [comment]
I need to catch up on how everything works, would be nice to be able to contribute back on this...it's a really nice application.  I'll lock into 5.0 next time

**Comment by lilingxi01** [comment]
I am having this issue with `Prisma 4.16.2`, as same as the poster of this issue. I think most recent threads are focusing on adapting 5.x.x but errors are also happening on 4.16.x  :(

**Comment by chrishoermann** [comment]
I just realized that changing the behaviour to meet the type requirements of prisma `5.1.1` introduced bugs in prior versions. I need to dig into this a bit on the weekend to get this sorted out.

**Comment by samrocksc** [comment]
Updating versions I've tried this with and whether it fails or not for you.

**Comment by samrocksc** [comment]
In the code referenced above, is the version of prisma passed into that function anywhere?  We could just do a version check and apply backwards.  I still haven't had a chance to peak at this.

**Comment by chrishoermann** [comment]
I implemented a version check yesterday in 2.7.9 but haven't testes it with a monorepo yet. it shoud work in a standard project where the package.json is located in the working directory.

**Comment by samrocksc** [comment]
works fine ;o) By the way, just tested it.  In the future I'll be able to PR against these.

**Comment by chrishoermann** [comment]
closing since this should not be a problem anymore with the current versions of the generator and prisma
