### ISSUE TITLE
Colons break custom imports.

### ISSUE THREAD

**Issue by alex-wellbelove** [chrishoermann/zod-prisma-types#179]
This:
```prisma
/// @zod.import(["import { Buffer } from 'node'"])
model MyModel { 
...
```

correctly adds the import to the generated file. 

However, this:
```prisma
/// @zod.import(["import { Buffer } from 'node:buffer'"])
model MyModel { 
...
```

instead includes the comment in the output:

```typescript
/**
 * @zod.import(["import { Buffer } from 'node:buffer'"])
 */
export const MyModel
```

and does not add the import to the generated output.

My usecase is:

https://developers.cloudflare.com/workers/runtime-apis/nodejs/buffer/

**Comment by Nerih** [comment]
can you try: 

 * @zod.import(["import { Buffer } from 'node\:buffer'"])

**Comment by Nerih** [comment]
i also noticed that @ is not supported either, which would be really cool.

**Comment by chrishoermann** [comment]
@Nerih thiws should work in `2.7.13` now
