### ISSUE TITLE
Support for Special Characters in Custom Error Messages

### ISSUE THREAD

**Issue by weleo** [chrishoermann/zod-prisma-types#186]
Please add support for special characters like `Ü`, `Ö`, and `Ä` in custom error messages. For example, in the given code snippet:

```prisma
email  String?  @unique  /// @zod.string.email({ message: "Ungültige E-Mail-Adresse" })
```

Currently, when these characters are included, the generated output gets commented out, as shown below:

```ts
/**
 * .email({ message: "Ungültige E-Mail-Adresse" })
 */
email: z.string().nullable(),
```

**Comment by chrishoermann** [comment]
As an Austrian how could I miss this 😅 I think I write too little Arnie quouts as error messages 🤔 Äktschn! should be working in `2.7.11`
