### ISSUE TITLE
 Infinite Execution in Vercel Installation Command with Zod Generator [BUG]

### ISSUE THREAD

**Issue by julio-ccatb** [chrishoermann/zod-prisma-types#217]
When deploying T3 app to Vercel using the Zod generator, the `install` command runs indefinitely, most likely because Vercel cannot find the `npx zod-prisma-types` command as a valid command. However, it doesn't crash for some reason until the default Vercel timeout occurs and closes it.

**Screenshots**
![image](https://github.com/chrishoermann/zod-prisma-types/assets/75903845/50d06115-66b4-4af7-b93a-8d4bebdfc16f)

**To reproduce**
 - Create a NextJS aplication using `create-t3-app t3-app`
 - Provide it with minimal confuguration adding `prisma`
 - Add the generator using using any pakage manager `npm i zod-prisma-types`
 - Add the generator to the schema like below
 - Upload the project to vercel

```Prisma
generator zod {
  provider = "npx zod-prisma-types"
} 
```

**Fix**

```Prisma
generator zod {
  provider = "zod-prisma-types"
} 
```

**Package versions (please complete the following information):**
 - zod: 3.22.4
 - prisma: 5.1.1
 - next: 14.0.3

**Note**

While it's unclear if this behavior stems from a misuse on my end, for the benefit of others encountering this issue, there should ideally be a flag or documentation update within the usage section to address this.

--

**Comment by CyanoFresh** [comment]
probably related https://github.com/chrishoermann/zod-prisma-types/issues/170
