### ISSUE TITLE
[BUG] Generated schemas contain Typescript error

### ISSUE THREAD

**Issue by Flusinerd** [chrishoermann/zod-prisma-types#222]
**Describe the bug**
After running ``prisma generate`` the generated typescript file contains typescript errors that prevent building.

**Screenshots**
![image](https://github.com/chrishoermann/zod-prisma-types/assets/22977969/0befccf1-0376-40cd-8689-f36722e8a2ba)

![image](https://github.com/chrishoermann/zod-prisma-types/assets/22977969/d1958973-93c4-49d6-8dad-a11a02feb87a)

![image](https://github.com/chrishoermann/zod-prisma-types/assets/22977969/991c911d-fa71-42ff-b28e-f8c9f4a4fdf3)

![image](https://github.com/chrishoermann/zod-prisma-types/assets/22977969/59292bd7-975c-4a80-929a-86c788b3034a)

**Package versions (please complete the following information):**
 - zod: 3.22.4
 - prisma: 5.7.0

**Additional context**
My schema:

```prisma
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
}

generator zod {
  provider = "zod-prisma-types"
  output   = "../../../libs/models/src/lib/prisma"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Session {
  session   String   @id
  userId    String   @db.Uuid
  expiresAt DateTime
  createdAt DateTime @default(now())
  user      User     @relation(fields: [userId], references: [id])
}

model User {
  id          String    @id @default(uuid()) @db.Uuid
  email       String    @unique
  password    String
  firstName   String
  lastName    String
  displayName String
  location    String?
  bio         String?
  createdAt   DateTime  @default(now())
  updatedAt   DateTime  @updatedAt
  Sessions    Session[]
}
```

**Comment by Flusinerd** [comment]
https://github.com/Flusinerd/clouts
This is the repo url. 
The generated file is in the ``libs/models...`` folder

**Comment by nordowl** [comment]
Facing the same error

**Comment by nordowl** [comment]
The issue seems to be caused by `zod` versions higher than `3.21.1`. See [this issue I found](https://github.com/electric-sql/electric/pull/700).
Changing my `zod` version to `3.21.1` resolved the error.

**Comment by chrishoermann** [comment]
@Flusinerd @nordowl yes this is a bug in zod versions higher than `3.21.1`. To support the latest version you can use the [useTypeAssertions](https://github.com/chrishoermann/zod-prisma-types?tab=readme-ov-file#usetypeassertions) option. But be aware that this circumvents the internal type checking. I use it in my own projects without any bugs so far but it can lead to bugs in the typesystem that are hard to debug

**Comment by andrewmartin** [comment]
Just wanted to say, thank you for documenting that you have the [useTypeAssertions](https://github.com/chrishoermann/zod-prisma-types?tab=readme-ov-file#usetypeassertions) available here. Stumbled on this thread and it helped a ton.
