### ISSUE TITLE
[BUG] Schema created with a forced `ZodType` which prevents using `ZodObject` methods

### ISSUE THREAD

**Issue by lambertkevin** [chrishoermann/zod-prisma-types#230]
**Describe the bug**
Due to the type explicitly added to each schema as `ZodType`, it's impossible to use methods attached to a `ZodObject` like `extends`, `merge` which prevents extending those schemas, or `strip` and `passthrough` which prevents override the `strict` method hardcoded to those schemas.

**Screenshots**
<img width="855" alt="Capture d’écran 2024-01-02 à 19 28 38" src="https://github.com/chrishoermann/zod-prisma-types/assets/44363395/5041ab2e-831f-4e4d-908c-e6fe3b3a9d16">

**The solution proposed by multiple zod github issues:**

<img width="512" alt="Capture d’écran 2024-01-02 à 19 31 37" src="https://github.com/chrishoermann/zod-prisma-types/assets/44363395/3afa88c8-a42f-4758-b4cf-bf416b234912">

**Package versions (please complete the following information):**
 - zod: "3.21.1"
 - prisma: "3.1.6"

**Additional context**
`satisfies` is only available since TS 4.9 while zod requires 4.5+

**Comment by ashe0047** [comment]
I am facing this issue as well as I need to extend the User zodobject to include an additional password2 field for validation but cant since the extend is not available. Hopefully this can be fixed soon!

**Comment by chrishoermann** [comment]
Hey @lambertkevin, @ashe0047, as stated in the docs under known issues and limitations:

>The satisfies operator: As some people have pointed out the input and output schemas and some of the relation schemas are typed as z.ZodType<myType>. This is required by zod for recursice types to work properly as [stated in the docs](https://zod.dev/?id=recursive-types). This has the downside that some zod methods like .merge(), .omit(), etc. are not available on these types.

It would work for schemas that do not have relations but in my experience even the most simple database schemas have relations and this is where recursive types/schemas come into play.

for extending zodSchemas I'd suggest you use the generated modelSchemas. They do not have a z.ZodType annotation and therefore have all the object methods. It may be a bit more work to make them fit your needs but with the output of options like [createOptionalDefaultValuesTypes](https://github.com/chrishoermann/zod-prisma-types#createoptionaldefaultvaluestypes), [createRelationValuesTypes](https://github.com/chrishoermann/zod-prisma-types#createrelationvaluestypes), [createPartialTypes](https://github.com/chrishoermann/zod-prisma-types#createpartialtypes) you can taylor your own custom schemas.

**Comment by lambertkevin** [comment]
Thanks for the answer @chrishoermann ! Sorry for missing that part in the doc, my google skills are not that good anymore 😞
