### ISSUE TITLE
[BUG] `imports        = "import {validator} from 'validator';"` not generating the import into `zod.ts`

### ISSUE THREAD

**Issue by machuwey** [chrishoermann/zod-prisma-types#269]
**Describe the bug**
Hey, I don't know if i'm missing something, but the package is not importante in the generated `zod.ts` artifact.

**Screenshots**
![image](https://github.com/user-attachments/assets/3d55608d-4751-4e27-90b6-b29295f81a5d)
![image](https://github.com/user-attachments/assets/25d8cb7a-02bd-4cf0-848e-00dba6541c4a)

**Package versions (please complete the following information):**
 - zod: 3.23.8
 - prisma: 5.18.0

**Additional context**

**Comment by danieltorrer** [comment]
Hi @machuwey, how did you solve this? Im having the same issue

**Comment by D0nte53** [comment]
> Hi [@machuwey](https://github.com/machuwey), how did you solve this? Im having the same issue

Hello, I have the same issue. Were you able to find the cause?
