### ISSUE TITLE
Add validation in WhereUnique inputs

### ISSUE THREAD

**Issue by chrishoermann** [chrishoermann/zod-prisma-types#34]
Maybe It makes sense to allow validation in `whereUnique` Inputs because there the full information of the field needs to be provided.

**Comment by chrishoermann** [comment]
implemented

**Comment by MarkShawn2020** [comment]
thanks for your great job. 

---

however, it seems that the `validateWhereUniqueInput` doesn't work.

when I turn on `createInputTypes`, then it would generate the proper `XXWhereUniqueXX` schemas for me (while it also generates more ... )
