### ISSUE TITLE
Is there a way to import for custom prisma location?

### ISSUE THREAD

**Issue by pedropmedina** [chrishoermann/zod-prisma-types#36]
Hi, 

Is it possible to read the the generated prisma client from a custom output location. As of now  the generator speculates that the location of prisma is at `import * as PrismaClient from "@prisma/client";`

Thanks

**Comment by chrishoermann** [comment]
Currently not. But this is a good idea and should be not too much of a problem to implement.

**Comment by chrishoermann** [comment]
should work now with version 1.2.0

**Comment by pedropmedina** [comment]
Hey @chrishoermann ,

Thanks for the quick update. It's working! The only thing I noticed it's that you left behind some logs
```javascript
config { prismaClientPath: '../client' }
parsedConfig {
  useInstanceOfForDecimal: false,
  imports: [],
  createInputTypes: true,
  addInputTypeValidation: true,
  prismaClientPath: '../client'
}
```

**Comment by chrishoermann** [comment]
Thnx for the hint, I'll remove them.

**Comment by chrishoermann** [comment]
logs removed in v1.2.1

**Comment by chrishoermann** [comment]
Closing since it works in current version

**Comment by pedropmedina** [comment]
Hey Chris,

Quick question. Wouldn't you be able to auto locate the output location for the prisma client? I noticed [prisma-zod-generator](https://github.com/omar-dulaimi/prisma-zod-generator) does it. This way we wouldn't have to opt in for this option?

**Comment by chrishoermann** [comment]
Thanks for the hint @pedropmedina. I wasn't aware of that. I'm a bit short on time the next few days but I'll definitly look into this

**Comment by chrishoermann** [comment]
@pedropmedina the automatic detection of the prisma client location should work in `v1.3.6`.

**Comment by chrishoermann** [comment]
Hey @pedropmedina

sorry my bad. I used the wrong reference path when getting the relative path of the client. 
It should work in `v1.3.7` now.

**Comment by pedropmedina** [comment]
Np @chrishoermann. It's working correctly now. Thanks a lot for the quick response.

**Comment by chrishoermann** [comment]
You're welcome
