### ISSUE TITLE
Native enums are not recognized as valid type

### ISSUE THREAD

**Issue by kachar** [chrishoermann/zod-prisma-types#42]
While implementing a post status enum I stumbled upon the following error:

```
[@zod generator error]: 'nativeEnum' is not a valid validator type. [Error Location]: Model: 'Post', Field: 'status'.
```

Can you please guide me if there's a standard way to support the `nativeEnum` feature of Zod?

Docs: https://github.com/colinhacks/zod#native-enums

## Prisma schema

```prisma
datasource db {
  provider = "postgres"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

generator zod {
  provider = "zod-prisma-types"
  output   = "./zod"
}

model Post {
  /// @zod.string.uuid()
  id     String     @id @db.Uuid
  name   String
  /// @zod.nativeEnum(PostStatus)
  status PostStatus @default(draft)
}

enum PostStatus {
  draft
  published
  archived
}
```

**Comment by chrishoermann** [comment]
Hey @kachar 

native enums are automatically generated by the generator based on the prisma enums so you do not have to use any `@zod` validator

for example your 

```prisma
enum PostStatus {
  draft
  published
  archived
}
```

should generate a corresponding zod native enum

```ts
export const PostStatusSchema = z.nativeEnum(
  PrismaClient.Prisma.PostStatus,
);
```

this native enum is then used in all the other schemas that are created by the generator. If you wan't to get detailed information which zod schemas are created just look at the `index.ts` in your `outputFolder` (default `generated/zod/index.ts`)

**Comment by kachar** [comment]
Thanks for the detailed answer!

Closing the issue
