### ISSUE TITLE
Generate only scalar input types

### ISSUE THREAD

**Issue by kachar** [chrishoermann/zod-prisma-types#44]
I would like to suggest adding a feature that allows users to reduce the generated models to only include the unchecked input types. This would be useful for cases where the actual project needs are less than all the generated code, and we want to leverage the excellent typing of this package with the actual project needs.

In the current version, a Prisma schema with two related models results in 900 generated lines of code, but we use only 40 of them.

Examples of how this feature could be used:

- The ability to reduce the generated models to only include the unchecked (simple) input types would allow users to remove related models, such as `connect` and `createOrConnect`, that might not be needed in their projects. This would help to reduce the overall size of the generated code and make it easier to manage.
- Leveraging the only scalars `z.ZodType<PrismaClient.Prisma.PostUncheckedCreateInput>` type in the generated models would enable users to take advantage of the strong typing provided by the library, while still being able to customize the generated models to meet the specific needs of their projects.
- Allowing users to define the model relationships in their project source code, rather than in the generator output, would give them more control over the structure of their project and allow them to better organize their code. This would make it easier for users to maintain and modify their projects over time, and would also make it easier for others to understand and work with the code.

I've figured out that the most simple input type that can do the job is the `*CreateManyInput` as it contains no relations and it overlaps with the `*UncheckedCreateInput` for the scalar (not nested) fields.

I believe this feature would greatly improve the usability of the library and make it easier for users to integrate it into their projects. 

## Sample output

```prisma
model Post {
  /// @zod.string.uuid()
  id       String @id @default(uuid())
  /// @zod.string.trim().min(4).max(100)
  title    String
  /// @zod.string.trim().min(4).max(100)
  text     String
  /// @zod.string.uuid()
  authorId String
  author   Author @relation(fields: [authorId], references: [id])
}

model Author {
  /// @zod.string.uuid()
  id    String @id @default(uuid())
  name  String
  posts Post[]
}
```

```tsx
export const PostSchema = z.object({
  id: z.string().uuid(),
  title: z.string().trim().min(4).max(100),
  text: z.string().trim().min(4).max(100),
  authorId: z.string().uuid(),
});

export const AuthorSchema = z.object({
  id: z.string().uuid(),
  name: z.string(),
});

export const PostCreateManyInputSchema: z.ZodType<PrismaClient.Prisma.PostCreateManyInput> = z.object({
  id: z.string().uuid().optional(),
  title: z.string().trim().min(4).max(100),
  text: z.string().trim().min(4).max(100),
  authorId: z.string().uuid(),
}).strict();

export const AuthorCreateManyInputSchema: z.ZodType<PrismaClient.Prisma.AuthorCreateManyInput> = z.object({
  id: z.string().uuid().optional(),
  name: z.string(),
}).strict();
```

**Comment by chrishoermann** [comment]
Hey @kachar,

only generating the `CreateManyInputSchemas` would be quite a complex  endeavour because in the `prisma.dmmf` the input types are stored in a very entangeld way so it would be a bit of a filter madness to filter out only the `CreateManyInputSchemas` and check which related types (`IntFilters`, `StringFilters`, and so on) need to be generated alongside.

So idecided to  add an option in `1.4.0` to make `fields with default values` optional in the generated `model schemas`.
With this option the generated models from your example should be equal to the `CreateManyInputSchemas`.

```prisma
generator zod {
  // ...rest of config
  defaultValuesOptionalInModel = true // new option in generator
  createInputTypes             = false // default is true
}

model Post {
  /// @zod.string.uuid()
  id       String @id @default(uuid())
  /// @zod.string.trim().min(4).max(100)
  title    String
  /// @zod.string.trim().min(4).max(100)
  text     String
  /// @zod.string.uuid()
  authorId String
  author   Author @relation(fields: [authorId], references: [id])
}

model Author {
  /// @zod.string.uuid()
  id    String @id @default(uuid())
  name  String
  posts Post[]
}
```
The above model would only create the following `model schemas` (no Input types are generated at all) that now are equal to the `CreateManyInputSchemas`.

```ts
export const PostSchema = z.object({
  id: z.string().uuid().optional(),
  title: z.string().trim().min(4).max(100),
  text: z.string().trim().min(4).max(100),
  authorId: z.string().uuid(),
});

export const AuthorSchema = z.object({
  id: z.string().uuid().optional(),
  name: z.string(),
});
```

only the `.strict()` option is missing that can be easily added manually if needed:

```ts
PostSchema.strict().parse(MyObjectToParse)
```

the only downside is that also the `ArgTypes` are not generated since they rely on the input types to be generated.

**Comment by kachar** [comment]
@chrishoermann That's a nice idea!

At the moment we're solving it with the following code:

```tsx
export const optionalId = <T extends z.ZodRawShape>(inputSchema: z.ZodObject<T>) => {
  return inputSchema.merge(
    z.object({
      id: z.string().optional(),
    }),
  )
}
```

```tsx
const createSchema = optionalId(AuthorSchema) // id is optional on create
const updateSchema = AuthroSchema // id is mandatory on update
```

**Comment by chrishoermann** [comment]
@kachar good solution and now I understand your usecase. Maybe it makes sense that we create an `optional` and `nonOptional` version when generating the models:

```ts
export const PostSchema = z.object({
  id: z.string().uuid().optional(),
  title: z.string().trim().min(4).max(100),
  text: z.string().trim().min(4).max(100),
  authorId: z.string().uuid(),
});

export const PostOptionalDefaultsSchema = PostSchema.merge(
  z.object({
    id: z.string().optional(),
    // ... all other keys with default values are made optional here
  }),
);
```

This is not that much work to implement and the schema would only be created when the user opts in via `defaultValuesOptionalInModel = true` so it does not create unnecessary schema types for users who don't need them.

**Comment by kachar** [comment]
That sounds even better :raised_hands: - to have both optional and non-optional side by side as they are used in different contexts.

I'm using `zod-prisma-types` along with tRPC, so having the well-typed router definitions for frontend/backend synchronization when doing CRUD actions means a lot.

I hope this feature would be useful to others besides my own use-case.

**Comment by chrishoermann** [comment]
@kachar 

The described functionality should now be available in `1.5.0`.

just add 

```prisma
generator zod {
  // ...rest of config
  createOptionalDefaultValuesTypes = true
}
```

to your generator config and a separate type named `[myModelName]OptionalDefaultsSchema` is created.
I removed the `defaultValuesOptionalInModel` option in favor of the above.

**Comment by kachar** [comment]
@chrishoermann Thanks for investing time and energy into this :bowing_man: 

I've just tested out `v1.5.0` and the results in your lib tests and the actual usage differ. I don't get the `.optional()` in the optional default schemas.

Do I do something wrong?

```prisma
model Initiative {
  /// @zod.string.uuid()
  id              String      @id @default(dbgenerated("gen_random_uuid()")) @db.Uuid
  /// @zod.string.trim().min(2).max(50)
  name            String
  /// @zod.string.uuid()
  createdByUserId String      @map("created_by_user_id") @db.Uuid
  createdByUser   User        @relation(fields: [createdByUserId], references: [id])

  createdAt  DateTime @default(now()) @map("created_at")
  updatedAt  DateTime @updatedAt @map("updated_at")
  isArchived Boolean  @default(false) @map("is_archived")
  isDeleted  Boolean  @default(false) @map("is_deleted")
}
```

```ts
// INITIATIVE
//------------------------------------------------------

export const InitiativeSchema = z.object({
  id: z.string().uuid(),
  name: z.string().trim().min(2).max(50),
  createdByUserId: z.string().uuid(),
  createdAt: z.date(),
  updatedAt: z.date(),
  isArchived: z.boolean(),
  isDeleted: z.boolean(),
});

export const InitiativeOptionalDefaultsSchema = InitiativeSchema.merge(
  z.object({
    id: z.string().uuid(),
    createdAt: z.date(),
    isArchived: z.boolean(),
    isDeleted: z.boolean(),
  })
);
```

One minor note - the [`@updatedAt`](https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#updatedat) is handled by Prisma, so it may behave as if it has a default value.

**Comment by kachar** [comment]
Also I've got an empty merge zod object for few of the generated models:


```prisma
model Label {
  name           String          @id @db.Citext
  description    String?
}
```

```ts
export const LabelSchema = z.object({
  name: z.string(),
  description: z.string().nullish(),
});

export const LabelOptionalDefaultsSchema = LabelSchema.merge(
  z.object({
  })
);
```

**Comment by chrishoermann** [comment]
@kachar thanks for the report. I obviously shouldn't release stuff when I'm tired :sleeping:

I forgot to remove the old `defaultValuesOptionalInModel` from my internal config but used it in one of my classes to check if the field should be optional. So no optional was added :expressionless:

Should work now in `1.5.3` 

Also `@updateAt` is now handeld properly as optional and the empty merge objects are not generated anymore.

**Comment by kachar** [comment]
@chrishoermann It works marvelously, kudos for the fast reaction :zap: 

I think we can close the issue if that's okay by you.

**Comment by chrishoermann** [comment]
@kachar glad to hear that. I'm closing it now.
