### ISSUE TITLE
TableIncludeSchema for Table without relationship

### ISSUE THREAD

**Issue by ionmoraru-toptal** [chrishoermann/zod-prisma-types#45]
when generating types with `createInputTypes=true` and the PrismaSchema has no relationship it generate and `include: TableIncludeSchema.optional(),` for it which doesn't exist.
```
prisma/zod/index.ts:12052:12 - error TS2304: Cannot find name 'TableIncludeSchema'.

12052   include: TableSchema.optional(),
```

**Comment by chrishoermann** [comment]
Hey @ionmoraru-toptal, thx for the report. Do you have an example `prisma schema` where this happens so i can try to reproduce the issue?

**Comment by ionmoraru-toptal** [comment]
from description above `Table` => `NetworkStats`

```ts
enum NetworkName {
  A
  B
}

model NetworkStats {
  id                  String      @id @default(uuid())
  network             NetworkName @default(A)
  circulatingSupply   Decimal?
  foundationSupply    Decimal?
  inflationAuthorized Decimal?
  inflatableBalance   Decimal?
  ftsoPrice           BigInt?
  ftsoSymbol          String?
  datePoint           DateTime
  createdAt           DateTime    @default(now())
  updatedAt           DateTime    @updatedAt

  @@unique([network, datePoint])
}
```

thanks, and tell me if I can help in some way

**Comment by chrishoermann** [comment]
@ionmoraru-toptal which version are you using and on which `schema` is the include option added?

When I run the generator on the current version (1.4.0) no include options are generated on the `argTypes` and no type error is thrown.

**Comment by chrishoermann** [comment]
Closing. Please reopen if this is still an issue
