### ISSUE TITLE
Default validator for int

### ISSUE THREAD

**Issue by kaeon** [chrishoermann/zod-prisma-types#47]
Hi, love this library, I migrated from zod-prisma and this works even better for me.

One issue I have is that the default validator for Int seems to be z.number() while it would be much easier making it z.number().int() so we don't have to type these rules manually in the schema. Any reason for this?

**Comment by chrishoermann** [comment]
hey @kaeon, thx for pointing this out. I did't think about that, but it's actually a very good idea. I'll keep you updated when it's implemented.

**Comment by chrishoermann** [comment]
@kaeon

With version `1.6.0` the generator now adds default validators in the following use cases:

```prisma
model WithDefaultValidators {
  id      String @id @default(cuid())
  idTwo   String @default(uuid())
  integer Int
}
```

```ts
export const WithDefaultValidatorsSchema = z.object({
  id: z.string().cuid(),
  idTwo: z.string().uuid(),
  integer: z.number().int(),
});
```

These defaults are overwritten when using a custom validator or when you opt out of using a default validator on a specific field:

```prisma
model WithDefaultValidators {
  id      String @id @default(cuid()) /// @zod.string.noDefault()
  idTwo   String @default(uuid()) /// @zod.string.noDefault()
  integer Int    /// @zod.number.noDefault()
}
```

```ts
export const WithDefaultValidatorsSchema = z.object({
  id: z.string(),
  idTwo: z.string(),
  integer: z.number(),
});
```

You can opt out of this feature completly by passing false to the config option.

```prisma
generator zod {
  // ...rest of config
  useDefaultValidators = false
}
```

If you have some further ideas for default validators feel free to open an issue.

**Comment by kaeon** [comment]
@chrishoermann thanks for the quick reply and implementation! Works fine and the cuid and uuid additions are also very handy.

**Comment by chrishoermann** [comment]
@kaeon you're welcome. I'll close this issue now
