### ISSUE TITLE
Incorrect @id field type

### ISSUE THREAD

**Issue by pedropmedina** [chrishoermann/zod-prisma-types#50]
It seems as if @id are expected to be `z.number` type even though it is defined as a `String` which is erroring out since `z.string().int()` is incorrect.

```javascript
// prisma schema
model CustomerSalesTeam {
 // ... fields
  id           String    @id
  // ...fields
}


// generated schema
export const CustomerSalesTeamWhereUniqueInputSchema: z.ZodType<PrismaClient.Prisma.CustomerSalesTeamWhereUniqueInput> = z.object({
  id: z.string().int().optional(),
}).strict();

```

**Comment by chrishoermann** [comment]
@pedropmedina thats wired.

I tried the above model and for me it created the right schema:

```ts
export const CustomerSalesTeamWhereUniqueInputSchema: z.ZodType<PrismaClient.Prisma.CustomerSalesTeamWhereUniqueInput> = z.object({
  id: z.string().optional(),
}).strict();
```

has this Id field been an int once? 

Not directly related but once I ran into an issue that prisma did not generate `DateTime` types in the prisma `index.d.ts` anymore but generated that model schemas. I don't know what caused this issue but I solved it by deleting all `node_modules` folders including the generated prisma client and reinstalled everything. maybe this is something you could try and see if the issue persists?

**Comment by pedropmedina** [comment]
I don't think it was a int ever @chrishoermann  . I have deleted node_modules, generated files several times, but nothing seems to work.

**Comment by chrishoermann** [comment]
@pedropmedina with 1.6.2 the option `useDefaultValidators` was added ([see docs](https://github.com/chrishoermann/zod-prisma-types#usedefaultvalidators)). You can disable this behaviour by adding

```prisma
generator zod {
  // ...rest of config
  useDefaultValidators = false
}

// or with @zod

model CustomerSalesTeam {
 // ... fields
  id           String    @id /// @zod.string.noDefault()
  // ...fields
}
```

The strange thing is that when generating the default validator the generator checks if the type of the field is an `Int` and only then adds the `.int()` validator. You mentioned in issue #49  that you use multiple prisma schemas? Is there somewhere a model with the same name but a different `id` type in another schema?

**Comment by pedropmedina** [comment]
That was it @chrishoermann . I disabled it for now. In this monorepo there's only a single prisma schema at this time so that shouldn't be the problem.

**Comment by pedropmedina** [comment]
Thank you @chrishoermann. 
I ran into another issue regarding relationships where the same schema get imported twice in the same file. Take as an example the Contact model below:
```javascript
model Contact {
  id                     Int       @id @unique
  
  company                Int?
 
  defaultBillingAddressRef    ContactAddressBookEntityAddress? @relation("default_billing_address_ref", fields: [defaultBillingAddress], references: [nkey])
   
 defaultShippingAddressRef   ContactAddressBookEntityAddress? @relation("default_shipping_address_ref", fields: [defaultShippingAddress], references: [nkey])
 ...
```

Generates something like this:
```javascript
import { z } from 'zod';
import { type Prisma } from '@prisma/client/netsuite';
import { CountryArgsSchema } from '../outputTypeSchemas/CountryArgsSchema';
import { ContactAddressBookArgsSchema } from '../outputTypeSchemas/ContactAddressBookArgsSchema';
import { ContactFindManyArgsSchema } from '../outputTypeSchemas/ContactFindManyArgsSchema'; // <- duplicate
import { ContactFindManyArgsSchema } from '../outputTypeSchemas/ContactFindManyArgsSchema';  // <- duplicate
import { ContactAddressBookEntityAddressCountOutputTypeArgsSchema } from '../outputTypeSchemas/ContactAddressBookEntityAddressCountOutputTypeArgsSchema';

export const ContactAddressBookEntityAddressIncludeSchema: z.ZodType<Prisma.ContactAddressBookEntityAddressInclude> = z.object({
  countryRef: z.union([z.boolean(),z.lazy(() => CountryArgsSchema)]).optional(),
  contactAddressBookRef: z.union([z.boolean(),z.lazy(() => ContactAddressBookArgsSchema)]).optional(),
  contactsDefaultBillingAddressRef: z.union([z.boolean(),z.lazy(() => ContactFindManyArgsSchema)]).optional(),
  contactsDefaultShippingAddressRef: z.union([z.boolean(),z.lazy(() => ContactFindManyArgsSchema)]).optional(),
  _count: z.union([z.boolean(),z.lazy(() => ContactAddressBookEntityAddressCountOutputTypeArgsSchema)]).optional(),
}).strict()

export default ContactAddressBookEntityAddressIncludeSchema;
```
