### ISSUE TITLE
Prisma generator generates empty index.ts file or empty files in directories

### ISSUE THREAD

**Issue by mikepage** [chrishoermann/zod-prisma-types#67]
I have created a new repository with `create-t3-app@7.4.0` and added this generator. It generates empty files since version 2.0.

First commit (install package)
https://github.com/mikepage/my-t3-app/commit/d7a1fed9f887b5a8a232f0b2fe241038ecce295b

Second commit
https://github.com/mikepage/my-t3-app/commit/cc617936221a3d31094d4cf1287313cd1a9ab421

No exceptions are thrown at `npx prisma generate`.

```
my-t3-app@0.1.0 /Users/mikepage/git/mikepage/my-t3-app
├── @next-auth/prisma-adapter@1.0.5
├── @prisma/client@4.9.0
├── @tanstack/react-query@4.24.4
├── @trpc/client@10.9.1
├── @trpc/next@10.9.1
├── @trpc/react-query@10.9.1
├── @trpc/server@10.9.1
├── @types/node@18.11.18
├── @types/prettier@2.7.2
├── @types/react-dom@18.0.10
├── @types/react@18.0.27
├── @typescript-eslint/eslint-plugin@5.50.0
├── @typescript-eslint/parser@5.50.0
├── autoprefixer@10.4.13
├── eslint-config-next@13.1.6
├── eslint@8.33.0
├── next-auth@4.19.1
├── next@13.1.6
├── postcss@8.4.21
├── prettier-plugin-tailwindcss@0.2.2
├── prettier@2.8.3
├── prisma@4.9.0
├── react-dom@18.2.0
├── react@18.2.0
├── superjson@1.9.1
├── tailwindcss@3.2.4
├── typescript@4.9.5
├── zod-prisma-types@2.0.2
└── zod@3.20.2
```

**Comment by chrishoermann** [comment]
@mikepage can you please try version `2.0.3`? I changed `fs.writeFile` to `fs.writeFileSync` hopefully this solves the issue.

**Comment by mikepage** [comment]
Great! This solves the issue :)

https://github.com/mikepage/my-t3-app/commit/d548ebda9494ef32afc11cbea264a15b6e841d31
