### ISSUE TITLE
Setting arrays of enums length

### ISSUE THREAD

**Issue by cellulosa** [chrishoermann/zod-prisma-types#69]
Thanks for the great library!

I have the following model

```
model Game {
    dice DieEnum[] @default([one, one, one])
}

enum DieEnum {
  one
  two
  three
  four
  five
  six
}
```

I want the `dice` field to have only three items, which programmatically I would write as:

```
z.object({
    dice: z.nativeEnum(DieEnum).array().length(3),
})
```

Is there a way to achieve this with `zod-prisma-types`?

Thanks

**Comment by chrishoermann** [comment]
@cellulosa This would make a good enhancement but currently it is not possible to add validators to enums or add `lenght` to a list field. I'll think about how this could be implemented and keep you updated.

**Comment by chrishoermann** [comment]
@cellulosa I implemented the functionality of adding array methods in `v2.3.2`. see [docs](https://github.com/chrishoermann/zod-prisma-types#array-validators) for more information.

**Comment by chrishoermann** [comment]
@cellulosa currently not, but I can adjust the regex to accept this kind of annotation.

**Comment by chrishoermann** [comment]
@cellulosa the array validators should now accept strings in the latest version.

**Comment by cellulosa** [comment]
It does! Thank you @chrishoermann it works like a charm!! Great work 🙌

**Comment by chrishoermann** [comment]
you're Welcome!
