### ISSUE TITLE
Skip @zod generator error to work with imported values

### ISSUE THREAD

**Issue by cellulosa** [chrishoermann/zod-prisma-types#70]
I have a file where I keep app-wide default values:

```
export const defaults = {
    max: 10
};
```

Which I have been using also with zod to do things like:

```
z.object({
    turn: z.number().positive().max(defaults.max),
})
```

If I import my file following the suggested syntax I am still unable to compile:

```
/// @zod.import(["import { defaults } from '../../../src/lib/defaults';"])
...
turn    Int    @default(1) /// @zod.number.positive().lt(defaults.max)
```

Since it throws (rightly so) a blocking error saying: `[@zod generator error]: Could not match validator 'lt' with validatorPattern '.lt(defaults'. Please check for typos!`

Perhaps there could be a way to allow Typo Errors?

**Comment by chrishoermann** [comment]
@cellulosa you can try [custom validators](https://github.com/chrishoermann/zod-prisma-types#custom-validators) like `/// @zod.custom.use(z.number().positive().lt(defaults.max))`.

**Comment by cellulosa** [comment]
> 

ah lovely that worked! Apologies I missed this
