### ISSUE TITLE
Custom imports failing  

### ISSUE THREAD

**Issue by binary-birthday** [chrishoermann/zod-prisma-types#71]
I was using v1 where custom imports where specified on the imports field of the generator block and that was working fine.

After updating to v2 and using

```
/// @zod.custom.imports(["import validator from 'validator'"])
model User {
  ///@zod.custom.use(z.string().uuid())
  id          String     @id @default(dbgenerated("gen_random_uuid()")) @db.Uuid
  ///@zod.custom.use(z.string().refine(val => validator.isMobilePhone(val), "Must be a valid Phone Number"))
  phoneNumber String     @unique
}
```

The generated file now no longer contains the custom import.

I'm using esm and typescript.

**Comment by chrishoermann** [comment]
@binary-birthday sorry there is a mistake in the docs: it should be `@zod.import(["... your import"])` instead of `@zod.custom.import(["... your import"])`. I'll fix it immediately

**Comment by chrishoermann** [comment]
Nice to hear that and you're welcome 😉 Closing this now
