### ISSUE TITLE
Inferred Types

### ISSUE THREAD

**Issue by luke-cbs** [chrishoermann/zod-prisma-types#74]
# Issue

I am wanting to generate the inferred type from our Prisma models as well as the Schema itself.
Currently I would have to create the types myself. These could simply just be one to ones of the generated Schema. Not sure if this is already available or I missed something.

**Comment by chrishoermann** [comment]
@luke-cbs since the types are based on the prisma types, could you not just use the pypes from the `prisma index.d.ts`? 
But, if not,  it is actually not that much work to add the inferred type to the model. I'll consider it on the next release.

**Comment by luke-cbs** [comment]
So came across your library to generate the zod types for me based of the models and just create a single source of truth. Using the prisma types directly introduces other issues when passing types around that don't match and stuff. So at the moment I take your generated schema's and then just infer them myself. Was just trying to see if we could get that out the box.

**Comment by chrishoermann** [comment]
@luke-cbs in the latest version the inferred type is now added by default. It is named after the prima model. No Suffix.

**Comment by luke-cbs** [comment]
You are a magician. Thank you
