### ISSUE TITLE
Field generated as z.string().int()

### ISSUE THREAD

**Issue by ciscoheat** [chrishoermann/zod-prisma-types#76]
Hello, thanks for this project, I just tried it and most things seems fine, but for some reason in one model, the type for the `status` field in the `CreateInputSchema` type is generated as `z.string().int()`.

**Schema:**
```prisma
model RaceResult {
  entryId Int       @id
  entry   RaceEntry @relation(fields: [entryId], references: [id])

  points Int
  rank   Int
  status String?

  @@map("raceresult")
}
```

**Generates:**
```ts
export const RaceResultCreateInputSchema: z.ZodType<Prisma.RaceResultCreateInput> = z.object({
  entry: z.lazy(() => RaceEntryCreateNestedOneWithoutRaceResultInputSchema),
  points: z.number(),
  rank: z.number(),
  status: z.string().int().optional().nullable(),
}).strict();
```

In `RaceResultSchema`, it's generated as expected: `z.string().nullable()`.

By renaming the field to `status2`, it's generated as expected.

**Comment by chrishoermann** [comment]
@ciscoheat This is an issue that for some people occur but I never could reproduce the issue. So currently I don't know why this happens. Have you tried a different order of the fields in the model?

**Comment by ciscoheat** [comment]
I tried any ordering, but the error persists, even for a simple model like this:

```prisma
model RaceResult {
  status  String
  entryId Int    @id
}
```

But renaming the field to `Status` makes it work again. Is lowercase `status` a reserved word somewhere?

**Comment by chrishoermann** [comment]
@ciscoheat  that is odd. I can not reproduce the issue when using your model and in the generator the word `status` is not reserved - at least not intentionally. did you try it in a new repo?

**Comment by adamgammell** [comment]
Seeing a similar same issue here. 
I am using the same field name in two models but different types and there is a relation between the two models.

For example:

```
model Practice {
  id           Int    @id @unique() @default(autoincrement())
  profilePhoto Int?
  user         User[]
}

model User {
  id           Int       @id @unique() @default(autoincrement())
  name         String?   
  profilePhoto String?   @db.Text
  practiceId   Int?
  practice     Practice? @relation(fields: [practiceId], references: [id])
}
```

will generate the following

Prisma Client:
```
  export type UserCreateManyPracticeInput = {
    id?: number
    name?: string | null
    profilePhoto?: string | null
  }
```

zod type
```
export const UserCreateManyPracticeInputSchema: z.ZodType<Prisma.UserCreateManyPracticeInput> = z.object({
  id: z.number().int().optional(),
  name: z.string().optional().nullable(),
  profilePhoto: z.string().int().optional().nullable(),
}).strict();
```

**Comment by chrishoermann** [comment]
@adamgammell thanks, I could reproduce the bug with your schema. I'll look into this and report back.

**Comment by chrishoermann** [comment]
@ciscoheat  @adamgammell this bug should now be fixed in the latest version. There was a bug wehn linking the `model` and the `inputType` form which the `create`, `update`, etc. schemas are created.

**Comment by ciscoheat** [comment]
Glad to hear that! I was really curious about the reason for this strange bug. :)
