### ISSUE TITLE
@zod.string.regex not working

### ISSUE THREAD

**Issue by ciscoheat** [chrishoermann/zod-prisma-types#78]
I noticed that this doesn't parse as it should:

```prisma
model X {
  phone  String? /// @zod.string.regex(/^\+\d{10,}$/)
}
```
Output:
```ts
phone: z.string().nullable()
```

Trying to use `@zod.custom.use` made it even worse:

```prisma
phone     String? /// @zod.custom.use(z.string().regex(/^\+\d{10,}$/))
```
Output:
```ts
  /**
   * .regex(/^\+\d{10,}$/))
   */
  phone: z.string(.nullable(),
```

**Comment by chrishoermann** [comment]
@ciscoheat thanks for narrowing this down. I think I need to tweak the regex a bit to accept backslashes. I'll definitly see to it.

**Comment by chrishoermann** [comment]
@ciscoheat this should also work now in the latest version

**Comment by ciscoheat** [comment]
Works fine with 2.0.14!
