### ISSUE TITLE
@zod.import not working with $ in it

### ISSUE THREAD

**Issue by ciscoheat** [chrishoermann/zod-prisma-types#80]
Sorry for reporting a lot, it's just a great library that I'd love to use. :) 

SvelteKit has a special import path, `$lib`, which is convenient but I noticed that this library cannot handle a dollar sign in the import statement:

```prisma
/// @zod.import(["import { reg } from '$lib/schemas'"])
model Continent {
  id        String    @id
  name      String    @unique /// @zod.custom.use(reg("^test$"))
}
```

Output:
```ts
/**
 * @zod.import(["import { reg } from '$lib/schemas'"])
 */
export const ContinentSchema = z.object({
  id: z.string(),
  name: reg("^test$"),
})
```

**Comment by chrishoermann** [comment]
@ciscoheat no problem, I'm glad somone takes the time to report these issues. I checked and the regex that checks the import statementets doesn't allow a dollar sign yet. I'll add this in the next release (hopefully today)

**Comment by chrishoermann** [comment]
@ciscoheat in the latest release the imports with `$` should work now

**Comment by ciscoheat** [comment]
That's strange, I've updated but is getting this now when doing `npx prisma generate`:

```
Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
Error: spawn zod-prisma-types ENOENT
```

Went back to 2.0.8 and it works.

**Comment by chrishoermann** [comment]
@ciscoheat I encountered the same in my tests and I don't know why this is the case. There seems to be something a bit fucked up in this repo since the 2.0.8 release. version 2.0.11 is now at the same state as 2.0.8 but without the fixes of the latest versions. I'm working on getting this right.

**Comment by ciscoheat** [comment]
I understand, the package system is fragile... Reminds me of this interview with a senior JS developer: https://www.youtube.com/watch?v=Uo3cL4nrGOk

**Comment by chrishoermann** [comment]
Haha that's a good one 😆 
It seems that the master branch is somehow broken. I reimplemented the changes in my dev branch, published it and it works flawlessly - so that latest version on npm now does, at least in my tests, what it should. 

I just need to figure out now how to fix the master branch 😅

**Comment by ciscoheat** [comment]
With version 2.0.14 this still doesn't work:

```prisma
/// @zod.import(["import * as s from '$lib/schemas'"])
model Continent {
```

The difference is that the comment in the generated schema is gone, but no import is added unless I change it back to `../schemas`.

**Comment by chrishoermann** [comment]
Sorry, I think I forgot to add back changes I made earlier when trying to fix my git issues. should work now in `2.0.15`.

**Comment by ciscoheat** [comment]
Works now, thanks :)
