### ISSUE TITLE
Not generating `UserRelation` with createRelationValuesType: true

### ISSUE THREAD

**Issue by Brenndoerfer** [chrishoermann/zod-prisma-types#82]
Hi! Great package

It looks like that the `XxxRelation` schema is not being generated. I do have `createRelationValuesType` set to `true`.

My schema below:
```prisma
model User {
  id       Int    @id @default(autoincrement())

  organization    Organization? @relation(fields: [organization_id], references: [id])
  organization_id Int?
  vendor Vendor[] 

  @@map("users")
}
```

My generator 
```prisma
generator zod {
  provider                         = "zod-prisma-types"
  output                           = "../../../node_modules/@prisma/client-data-model/zod"
  createOptionalDefaultValuesTypes = true // default is false
  createRelationValuesType         = true // default is false
  useDefaultValidators             = true // default is true
  writeNullishInModelTypes         = true // default is false
  prismaClientPath                 = "../../client-data-model" //"./path/to/prisma/client" // default is client output path
}
```

It generates a `UserSchema`, `UserOptionalDefaultsSchema`, but **no** `UserRelations` schema - any idea why?

I am using

```json
"prisma": "^4.10.1",
"zod": "^3.20.2",
"zod-prisma-types": "^2.0.12",
"typescript": "~4.8.2"
```

**Comment by Brenndoerfer** [comment]
OK.. after spending way too much time figuring out what's going on..

Turns out a missing `s` in `createRelationValuesType`

Correct is `createRelationValuesTypes`

**Comment by chrishoermann** [comment]
Oh sorry, that's wrong in the docs. Thanks for pointing this out.

**Comment by Brenndoerfer** [comment]
Oh ok. I was wondering where I copied that wrong (assumed deleted a char by mistake). That gives me a bit piece of mind :)
