### ISSUE TITLE
model schema with optional properties, relations and relation properties

### ISSUE THREAD

**Issue by michiim** [chrishoermann/zod-prisma-types#83]
Thank you for your great work.

I use the model schemas for client side validation of user input. Often it happens that only parts of a schema need to be validated, e.g. when a user wants to change his address without possibility to change name/first name. In such a case it would be good to have a schema where all properties are optional. For the described case it would of course be possible to use zod-partial. But there are more complex examples where this does not work, because relations are loaded via lazy. For example, I have no way to use partial to modify a schema for an order so that the order items are validated too, but the relation to possible invoices or delivery bills are ignored.

I would like to be able to generate schemas where all properties are optional, including those of the relations (and the relations themselves as well).

**Comment by chrishoermann** [comment]
@michiim this seems like a useful enhancement. I'll see to it and report back once it's implemented (could take a few days)

**Comment by chrishoermann** [comment]
@michiim in the latest version you can now use the `createPartialTypes` generator option to create the required schemas. see [docs](https://github.com/chrishoermann/zod-prisma-types#createpartialtypes) for more information.

**Comment by michiim** [comment]
Thank you very much. Just bought you some coffee.

**Comment by chrishoermann** [comment]
@michiim I saw it just a few minutes ago. Big Thanks! 🙏
