### ISSUE TITLE
custom imports: multiple imports of same module not working (depending on space)

### ISSUE THREAD

**Issue by michiim** [chrishoermann/zod-prisma-types#84]
custom imports works depending on spaces

does work:
/// @zod.import(["import { myFunction,myFunction2 } from 'mypackage'"])
/// @zod.import(["import { myFunction } from 'mypackage'", "import { myFunction } from 'mypackage'"])

does not work:
/// @zod.import(["import { myFunction, myFunction2 } from 'mypackage'"])
/// @zod.import(["import { myFunction } from 'mypackage'","import { myFunction } from 'mypackage'"])

This happens because your split definition at line 209 in packages/generator/src/classes/extendedDMMFModel.ts:
const importsList = importStatements.groups?.['imports']?.split(', ');

**Comment by chrishoermann** [comment]
@michiim thanks for finding this issue. changed the split to a regex that should fix it in the latest release.

**Comment by michiim** [comment]
Great, thanks a lot.
