### ISSUE TITLE
Settings to skip generation of include and select fields

### ISSUE THREAD

**Issue by oceandrama** [chrishoermann/zod-prisma-types#85]
First of all, thanks for your project!

I'm using this package with trpc to generate inputs of procedures, like this
```js
findMany: t.procedure.input(ArticleFindManyArgsSchema).query(({ input}) => {
  return prisma.article.findMany(input);
}),
```
Unfortunately with current limitations of TS (https://github.com/trpc/trpc/discussions/2150, https://github.com/microsoft/TypeScript/issues/1213), it's impossible to correct infer return type if you are using `select` or `include`
```js
trpc.article.findMany.useQuery(select: {id: true}}) // return type is still Article not {id: number}
```
so, I want to explicit exclude `select` and `include` from input arguments
Unfortunately with current limitation of Zod (https://github.com/chrishoermann/zod-prisma-types/issues/79, https://github.com/chrishoermann/zod-prisma-types/issues/41) it's impossible to do something like this
```js
ArticleFindManyArgsSchema.omit({select: true, include: true})
```
so maybe you can extends settings like https://github.com/omar-dulaimi/prisma-zod-generator has (`isGenerateSelect` and `isGenerateInclude`) to omit this fields from schemas. Are there another solutions?

**Comment by chrishoermann** [comment]
@oceandrama Thanks for the suggestion. I wasn't aware that this does not work as expected. 

In the latest version you can now opt out of the features by adding `addIncludeType = false` and `addSelectType = false` to the generator config. See [docs](https://github.com/chrishoermann/zod-prisma-types#addincludetype).

I just removed the fields from the `[Model]ArgTypeSchemas` but the `include` and `select` schemas are still generated (if you have some use for it??)

**Comment by oceandrama** [comment]
@chrishoermann Wow, blazing fast! Thanks a lot, it works perfectly! I think it maybe usefull to save `include` and `select` schemas, but now I'm not using it
