### ISSUE TITLE
Incorrect schema type if using addIncludeType=false or addSelectType=false

### ISSUE THREAD

**Issue by oceandrama** [chrishoermann/zod-prisma-types#86]
With this settings
```
generator zod {
  provider       = "zod-prisma-types"
  addIncludeType = false
  addSelectType  = false
}
```
it generates
```js
export const ArticleFindUniqueOrThrowArgsSchema: z.ZodType<Prisma.ArticleFindUniqueOrThrowArgs> = z
  .object({
    where: ArticleWhereUniqueInputSchema,
  })
  .strict();
```
zod object is correct, but the type is `Prisma.ArticleFindUniqueOrThrowArgs` that still have `select` and `include` fields
I think it should be `Omit<Prisma.ArticleFindUniqueOrThrowArgs, "select" | "include">`

**Comment by chrishoermann** [comment]
@oceandrama yeah you're right - I totally forgot about that. In version `2.2.2` this should now work correctly.
