### ISSUE TITLE
NullableJsonInput should be imported as type

### ISSUE THREAD

**Issue by michiim** [chrishoermann/zod-prisma-types#87]
import { NullableJsonInput } from '../inputTypeSchemas/transformJsonNull';

should be

import { **type** NullableJsonInput } from '../inputTypeSchemas/transformJsonNull';

**Comment by chrishoermann** [comment]
@michiim thanks for the hint. Should be fixed in the latest version.

**Comment by michiim** [comment]
You are the fastest developer.
Thanks a lot
