### ISSUE TITLE
Build fails with Prisma 4.11.0 due to new `toFixed` method on `DecimalJsLike` interface.

### ISSUE THREAD

**Issue by sethmiller** [chrishoermann/zod-prisma-types#90]
I looked in the issues list and didn't find a duplicate of this issue.

## Issue
Prisma added a `toFixed` method to the DecimalJsLike interface. This causes compilation to fail when using `zod-prisma-types` with the following error.

```
prisma/generated/zod/index.ts:463:14 - error TS2322: Type 'ZodObject<{ equals: ZodOptional<ZodEffects<ZodUnion<[ZodNumber, ZodString, ZodObject<{ d: ZodArray<ZodNumber, "many">; e: ZodNumber; s: ZodNumber; }, "strip", ZodTypeAny, { ...; }, { ...; }>]>, string | ... 1 more ... | { ...; }, string | ... 1 more ... | { ...; }>>; ... 11 more ...; _max: ZodOptional<...>; }, "stri...' is not assignable to type 'ZodType<NestedDecimalWithAggregatesFilter, ZodTypeDef, NestedDecimalWithAggregatesFilter>'.
  The types of '_type.equals' are incompatible between these types.
    Type 'string | number | { d: number[]; e: number; s: number; } | undefined' is not assignable to type 'string | number | Decimal | DecimalJsLike | undefined'.
```

This error is resolved by rolling Prisma back to `4.10.0`.

## Reproduction
I made a repo to reproduce the issue but it should work with any schema that has a Decimal column.
* [main](https://github.com/sethmiller/zod-prisma-types-test) should build correctly
* [prisma-4.11-decimal-error](https://github.com/sethmiller/zod-prisma-types-test/tree/prisma-4.11-decimal-error) will fail to build with the above error

For convenience, the `schema.prisma` file is 
```prisma
generator client {
  provider = "prisma-client-js"
}

generator zod {
  provider = "zod-prisma-types"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
  num   Decimal
}
```

**Comment by chrishoermann** [comment]
@sethmiller Thanks for the report. I quickly looked into this and it seems that this is more work than I initially expected. Simply adding a `toFixed: z.function().return(z.string)` seems not to work because then Typescript somehow requires the `Prisma.Decimal` type with all the other 94 methods and does not simply accept every Object that meets the requirements of the interface.

I' don't know when I have the time to get to it but I'll definitly address this.

**Comment by sethmiller** [comment]
No worries. Thanks for the quick reply!

**Comment by chrishoermann** [comment]
@sethmiller I have a fix for this problem that generally works but one of my tests is failing. If I try to pass an object like 
```ts
export const decimalJsLikeOne: DecimalJsLike = {
  d: [1230000], // array of digits
  e: -1, // exponent
  s: 1, // sign
  toFixed: () => '1230000',
};
```
via trpc it seems that the to fixed method gets stripped out. I don't know why but it works with `new Decimal()`, `new Prisma.Decimal()`, numbers and strings. so the main usecases should be covered.

 can you please try it out on your end with `2.4.1-beta.0` before I release it into the world?

**Comment by sethmiller** [comment]
When testing against my [test repo](https://github.com/sethmiller/zod-prisma-types-test/tree/prisma-4.11-decimal-error), it is not able to resolve `DecimalJsLike`.

```
prisma/generated/zod/index.ts:11:45 - error TS2552: Cannot find name 'DecimalJsLike'. Did you mean 'DecimalJSLike'?

11 export const DecimalJSLikeSchema: z.ZodType<DecimalJsLike> = z.object({ d: z.array(z.number()), e: z.number(), s: z.number(), toFixed: z.function().args().returns(z.string()), });
```

The message is a little confusing since there is the type `DecimalJSLike` (with a capital S) is also defined in the file. That said, prefixing with `Prisma` (e.g. `Prisma.DecimalJsLike`) or importing `DecimalJsLike` (lowercase "s") from Prisma resolves the issue.

I haven't been able to test it beyond this simple use case, however (I haven't incorporated this package into a larger project just yet).

**Comment by chrishoermann** [comment]
Thanks for testing it out. I'll refine this a bit before officially releasing it.

**Comment by chrishoermann** [comment]
@sethmiller should be fixed now in the latest release
