### ISSUE TITLE
Generate sources throw error when using importsNotUsedAsValues tsconfig opion

### ISSUE THREAD

**Issue by juh9870** [chrishoermann/zod-prisma-types#96]
when `"importsNotUsedAsValues": "error"`, generated sources throw an error, because they use `import { type Prisma } from '@prisma/client';` instead of `import type { Prisma } from '@prisma/client';`

**Comment by chrishoermann** [comment]
@juh9870 I don't know what you mean by "they use `import { type Prisma } from '@prisma/client';`"?

The generator should generate `import type { Prisma } from '@prisma/client';`. Is this not the case on your end?

**Comment by juh9870** [comment]
Have just updated to 2.3.5, and problem still remains.
My prisma config:
```
generator zod {
  provider                  = "zod-prisma-types"
  createRelationValuesTypes = true
}
```
Full project: https://github.com/juh9870/library-backend

**Comment by chrishoermann** [comment]
@juh9870 sorry my bad. had some code fragments where the described import was used. should be fixed in the latest version.
